jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'

    metadata:
        directories:
        - name: App
          path: '%kernel.project_dir%/config/jms_serializer'
          namespace_prefix: 'App\Model'
